In [35]:
import re
import numpy as np
from SolvingAdvent.HelferWichtel import HelferWichtel as Wichtel

TagFile = '09Test'


Helfer = Wichtel()
PuzzleInput = ''.join(Helfer.getPuzzleInput(TagFile))
PuzzleInput = [line.replace(' ','') for line in PuzzleInput.split('\n')]
print([line.replace(' ','') for line in PuzzleInput])
print(re.findall('\D',PuzzleInput[1]))

['R4', 'U4', 'L3', 'D1', 'R4', 'D1', 'L5', 'R2']
['U']
[1 2 3]
[0 1 2 3 4]


In [149]:
class World:
    def __init__(self):
        xvalues = np.arange(-5,5)
        yvalues = np.arange(5,-5,-1)
        self.xx, self.yy = np.meshgrid(xvalues,yvalues)
        self.headPosition = [0,0]
        self.tailPosition = [0,0]
        self.tailHistory = np.array([[0],[0]])
        
    def getWorld(self):
        return self.xx, self.yy
    
    def extendMapNorth(self):
        self.xx = np.vstack([self.xx[0],self.xx])
        self.yy = np.vstack([self.yy[0]+1,self.yy])
        
    def extendMapEast(self):
        self.xx = np.hstack([self.xx, np.transpose([self.xx[:,-1]+1])])
        self.yy = np.hstack([self.yy, np.transpose([self.yy[:,-1]])])
        
    def extendMapSouth(self):
        self.xx = np.vstack([self.xx, self.xx[-1]])
        self.yy = np.vstack([self.yy, self.yy[-1]-1])
        
    def extendMapWest(self):
        self.xx = np.hstack([np.transpose([self.xx[:,0]-1]), self.xx])
        self.yy = np.hstack([np.transpose([self.yy[:,0]]), self.yy])
        
    def 



In [151]:
# Class Testing
newWorld = World()
xx, yy = newWorld.getWorld()
print(yy)
newWorld.extendMapWest()
xx,yy = newWorld.getWorld()
print(yy)

[[ 5  5  5  5  5  5  5  5  5  5]
 [ 4  4  4  4  4  4  4  4  4  4]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]]
[[ 5  5  5  5  5  5  5  5  5  5  5]
 [ 4  4  4  4  4  4  4  4  4  4  4]
 [ 3  3  3  3  3  3  3  3  3  3  3]
 [ 2  2  2  2  2  2  2  2  2  2  2]
 [ 1  1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4 -4]]


In [128]:
xvalues = np.arange(-5,5)
yvalues = np.arange(-5,5)
xx,yy = np.meshgrid(xvalues,yvalues)
print(xx)
xx = np.vstack([([xx[0]+1]),xx])
print(xx)


[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[[-4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]


In [139]:
print(xx[:,-1])
print(xx)
print(xx[:,-1])

[5 4 4 4 4 4 4 4 4 4 4]
[[-4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[5 4 4 4 4 4 4 4 4 4 4]


In [153]:
print(np.array([[1,1],[1,2]]))

[[1 1]
 [1 2]]
